server:
  port: 9020

zuul:
  routes:
    caculator:
      serviceId: calculator
      path: /calculator/**
      stripPrefix: true
    formula:
      serviceId: formula
      path: /formula/**
      stripPrefix: true
    cuboid:
      serviceId: cuboid
      path: /cuboid/**
      stripPrefix: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/